// priority: 0
console.info('[AMMONIUM@KUBEJS]: replace.js loaded')

ServerEvents.recipes(e => {
	e.replaceInput({id: 'create:crafting/kinetics/smart_fluid_pipe'}, 'create:electron_tube', 'create:filter')
    e.replaceInput({id: 'create:crafting/kinetics/mechanical_press'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'create:crafting/kinetics/encased_fan'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'create:crafting/kinetics/mechanical_mixer'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'rechiseledcreate:mechanical_chisel'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'create:crafting/kinetics/millstone'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'create:crafting/kinetics/mechanical_piston'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'create:crafting/kinetics/contraption_controls'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'createaddition:crafting/rolling_mill'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'create:crafting/kinetics/deployer'}, 'create:andesite_casing', 'kubejs:andesite_hull')
    e.replaceInput({id: 'immersiveengineering:crafting/cokebrick'}, '#forge:sandstone', 'create:andesite_alloy')
    // e.replaceInput({id: 'create:crafting/kinetics/fluid_tank'}, 'minecraft:barrel', 'create:copper_casing')
    e.replaceInput({id: 'mekanism:fluid_tank/basic'}, 'minecraft:iron_ingot', '#forge:ingots/steel')
    e.replaceInput({id: 'adminshop:buyer_1'}, 'minecraft:ender_chest', '#forge:chests')
    e.replaceInput({id: 'adminshop:seller'}, 'minecraft:ender_chest', '#forge:chests')
    e.replaceInput({id: 'create:crafting/kinetics/deployer'}, 'create:electron_tube', 'create:shaft')
    // e.replaceInput({id: 'pneumaticcraft:liquid_compressor'}, '#forge:leather', 'thermal:invar_plate')
    e.replaceInput({id: 'pneumaticcraft:solar_compressor'}, '#forge:gears/compressed_iron', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:manual_compressor'}, '#forge:ingots/compressed_iron', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:refinery'}, 'minecraft:redstone', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:refinery_output'}, 'minecraft:diamond', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:thermopneumatic_processing_plant'}, 'pneumaticcraft:pressure_tube', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:flux_compressor'}, '#forge:gears/compressed_iron', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:pneumatic_dynamo'}, '#forge:gears/compressed_iron', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:pneumatic_dynamo'}, 'pneumaticcraft:printed_circuit_board', 'createaddition:alternator')
    e.replaceInput({id: 'pneumaticcraft:fluid_mixer'}, 'pneumaticcraft:pressure_tube', 'kubejs:compressed_mech')
    e.replaceInput({id: 'compressedcreativity:crafting/rotational_compressor'}, 'create:brass_casing', 'kubejs:compressed_mech')
    e.replaceInput({id: 'pneumaticcraft:small_tank'}, '#forge:glass', 'create:fluid_tank')
    e.replaceInput({id: 'immersiveengineering:crafting/workbench'}, 'minecraft:iron_ingot', 'pneumaticcraft:plastic')
    e.replaceInput({id: 'immersiveengineering:crafting/blastbrick'}, 'minecraft:magma_block', 'pneumaticcraft:plastic')
    e.replaceInput({id: 'immersiveengineering:crafting/blueprint_components'}, 'minecraft:blue_dye', 'pneumaticcraft:plastic')
    e.replaceInput({id: 'immersiveengineering:crafting/light_engineering'}, 'minecraft:copper_ingot', 'immersiveengineering:component_electronic')
    e.replaceInput({id: 'immersiveengineering:crafting/heavy_engineering'}, '#forge:ingots/electrum', 'immersiveengineering:component_electronic')
    e.replaceInput({id: 'immersiveengineering:crafting/rs_engineering'}, 'minecraft:copper_ingot', 'immersiveengineering:component_electronic')
    e.replaceInput({id: 'thermal:machine_frame'}, '#forge:gears/tin', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'mekanismgenerators:generator/heat'}, 'minecraft:furnace', 'createaddition:alternator')
    e.replaceInput({id: 'mekanismgenerators:generator/wind'}, 'mekanism:basic_control_circuit', 'createaddition:alternator')
    e.replaceInput({id: 'mekanismgenerators:generator/solar'}, 'mekanism:energy_tablet', 'createaddition:alternator')
    e.replaceInput({id: 'minecraft:sticky_piston'}, 'minecraft:slime_ball', '#forge:slimeballs')
    e.replaceInput({id: 'ae2:network/blocks/inscribers'}, 'minecraft:copper_ingot', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'industrialforegoing:machine_frame_pity'}, 'minecraft:redstone_block', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'tiab:time_in_a_bottle'}, 'minecraft:clock', 'kubejs:compressed_mech')
    e.replaceInput({id: 'prettypipes:item_terminal'}, 'minecraft:ender_pearl', '#forge:ingots/gold')
    // e.replaceInput({id: 'create:crafting/kinetics/empty_blaze_burner'}, 'minecraft:netherrack', 'minecraft:magma_block')
    // e.replaceOutput({id: 'create:crafting/kinetics/empty_blaze_burner'}, 'create:empty_blaze_burner', 'create:blaze_burner')
    e.replaceInput({id: 'naturesaura:gold_fiber'}, 'minecraft:gold_nugget', 'naturesaura:gold_powder')
    // e.replaceInput({id: 'botania:fertilizer_dye'}, 'minecraft:bone_meal', 'botania:white_petal')
    e.replaceInput({id: 'naturesaura:bottle_two_the_rebottling'}, '#minecraft:planks', 'botania:livingwood_planks')
    e.replaceInput({id: 'naturesaura:offering_table'}, '#minecraft:logs', 'botania:livingwood_log')
    e.replaceInput({id: 'modularrouters:blank_module'}, 'minecraft:redstone', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'extendedcrafting:basic_table'}, 'minecraft:crafting_table', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'extendedcrafting:advanced_table'}, 'extendedcrafting:black_iron_slate', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'extendedcrafting:elite_table'}, 'extendedcrafting:black_iron_slate', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'extendedcrafting:ultimate_table'}, 'extendedcrafting:black_iron_slate', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'mekanism:metallurgic_infuser'}, '#forge:ingots/osmium', 'mekanism:steel_casing')
    e.replaceInput({id: 'thermal:machine_crystallizer'}, 'thermal:machine_frame', 'mekanism:steel_casing')
    e.replaceInput({id: 'mekanism:teleportation_core'}, 'minecraft:diamond', 'kubejs:sbc')
    e.replaceInput({id: 'thermal:augments/upgrade_augment_1'}, '#forge:gears/gold', 'immersiveengineering:component_electronic')
    e.replaceInput({id: 'mekanism:enrichment_chamber'}, 'mekanism:basic_control_circuit', 'kubejs:integrated_circuit')
    e.replaceInput({id: 'mekanismgenerators:reactor/glass'}, 'mekanism:enriched_iron', '#forge:dusts/steel')
    e.replaceInput({id: 'powah:crafting/capacitor_basic'}, 'minecraft:redstone_block', 'extendedcrafting:redstone_ingot')
    e.replaceInput({output: 'bigreactors:basic_reactorcontroller'}, 'minecraft:diamond', 'mekanism:steel_casing')
    e.replaceInput({output: 'bigreactors:reinforced_reactorcontroller'}, 'minecraft:diamond_block', 'mekanism:steel_casing')
    e.replaceInput({id: 'createaddition:mechanical_crafting/electric_motor'}, 'createaddition:capacitor', 'createendertransmission:energy_transmitter')
    e.replaceInput({id: 'souloverclockers:eye'}, 'minecraft:echo_shard', 'ars_nouveau:source_gem')
    e.replaceInput({id: 'souloverclockers:overclocker'}, 'minecraft:crying_obsidian', 'ars_nouveau:sourcestone')
    e.replaceInput({id: 'createchromaticreturn:multiplite_recipe'}, 'minecraft:shulker_shell', 'mekanism:ingot_refined_obsidian')
    e.replaceInput({id: 'naturesaura:generator_limit_remover'}, 'naturesaura:tainted_gold', 'kubejs:cryo_mainframe')
    e.replaceInput({id: 'createdieselgenerators:crafting/pumpjack_bearing'}, '#forge:ingots/zinc', 'kubejs:compressed_mech')
    e.replaceInput({id: 'prettypipes:low_retrieval_module'}, 'minecraft:ender_pearl', 'kubejs:basic_mech')
    e.replaceInput({id: 'thermal:fluid_cell'}, '#thermal:glass/hardened', '#forge:glass')
    e.replaceInput({id: 'functionalstorage:fluid_1'}, 'minecraft:bucket', 'thermal:fluid_cell')
    e.replaceInput({id: 'functionalstorage:fluid_2'}, 'minecraft:bucket', 'thermal:fluid_cell')
    e.replaceInput({id: 'functionalstorage:fluid_4'}, 'minecraft:bucket', 'thermal:fluid_cell')
    // e.replaceInput({input: 'createchromaticreturn:refined_mixture'}, 'createchromaticreturn:refined_mixture', 'kubejs:refined_mixture')
    // e.replaceInput({input: 'createchromaticreturn:shadow_essence'}, 'createchromaticreturn:shadow_essence', 'kubejs:shadow_essence')
    // e.replaceOutput({output: 'createchromaticreturn:refined_mixture'}, 'createchromaticreturn:refined_mixture', 'kubejs:refined_mixture')
    // e.replaceOutput({output: 'createchromaticreturn:shadow_essence'}, 'createchromaticreturn:shadow_essence', 'kubejs:shadow_essence')
    // e.replaceInput({id: 'ironjetpacks:wood_jetpack'}, 'ironjetpacks:strap', 'create_jetpack:netherite_jetpack')
    // e.replaceInput({id: 'create_jetpack:jetpack'}, 'minecraft:elytra', 'immersiveengineering:glider')
    e.replaceInput({id: 'entangled:block'}, '#forge:chests/wooden', 'mekanism:teleportation_core')
    e.replaceInput({id: 'functionalstorage:ender_drawer'}, 'minecraft:ender_chest', 'mekanism:teleportation_core')
    // e.replaceInput({id: 'integrateddynamics:special/part_connector_omni_directional'}, 'integrateddynamics:cable', 'mekanism:teleportation_core')
    e.replaceInput({id: 'irongenerators:certus_generator_rcp'}, 'minecraft:furnace', 'irongenerators:stone_generator')
    e.replaceInput({id: 'irongenerators:skystone_generator_rcp'}, 'minecraft:furnace', 'irongenerators:stone_generator')
    e.replaceInput({id: 'irongenerators:netherrack_rcp'}, 'minecraft:furnace', 'irongenerators:stone_generator')
    e.replaceInput({id: 'laserio:logic_chip_raw'}, '#c:quartz_blocks', 'kubejs:compressed_mech')
    e.replaceInput({id: 'projectred_expansion:electric_screwdriver'}, '#forge:gems/sapphire', 'kubejs:compressed_mech')
    e.replaceInput({id: 'projectred_fabrication:plotting_table'}, '#forge:gems/sapphire', 'kubejs:compressed_mech')
    e.replaceInput({id: 'adminshop:fluid_buyer'}, 'minecraft:ender_chest', '#forge:chests')
    e.replaceInput({id: 'thermal:servo_attachment_2'}, 'minecraft:redstone', 'kubejs:compressed_mech')
    e.replaceInput({id: 'thermal:fluid_duct_windowed_4'}, '#thermal:glass/hardened', '#forge:glass')
    e.replaceInput({id: 'thermal:turbo_servo_attachment_2'}, 'thermal:redstone_servo', 'thermal:servo_attachment')
    e.replaceInput({id: 'industrialforegoing:dissolution_chamber/advanced_machine_frame'}, '#forge:gears/diamond', 'kubejs:cryo_mainframe')
    e.replaceInput({id: 'createchromaticreturn:motor_recipe'}, 'create:rotation_speed_controller', 'kubejs:sentient_mainframe')
    e.replaceInput({id: 'createchromaticreturn:generator_recipe'}, 'createaddition:alternator', 'kubejs:sentient_mainframe')
    e.replaceInput({id: 'endportalrecipe:craftable_end_portal'}, 'minecraft:dragon_egg', 'pneumaticcraft:printed_circuit_board')
    // e.replaceInput({id: 'pneumaticcraft:patchouli_book_crafting'}, 'pneumaticcraft:ingot_iron_compressed', '#forge:ingots/compressed_iron')
    e.replaceInput({id: 'integrateddynamics:crafting/coal_generator'}, 'minecraft:furnace', 'irongenerators:stone_generator')
    e.replaceInput({id: 'integrateddynamics:crafting/variable'}, 'minecraft:paper', 'kubejs:compressed_mech')
    e.replaceInput({id: 'sfm:manager'}, 'minecraft:repeater', 'kubejs:compressed_mech')
    e.replaceInput({id: 'sfm:disk'}, 'minecraft:repeater', 'kubejs:compressed_mech')
    e.replaceInput({id: 'sfm:printing_press'}, 'minecraft:piston', 'kubejs:compressed_mech')
    e.replaceInput({id: 'cccbridge:source_block'}, 'create:cut_asurine', 'minecraft:polished_andesite')
    e.replaceInput({id: 'cccbridge:scroller_block'}, 'create:cut_asurine', 'minecraft:polished_andesite')
    e.replaceOutput({output: 'thermal:coal_coke'}, 'thermal:coal_coke', 'immersiveengineering:coal_coke')
    
})
