// priority: 0
console.info('[AMMONIUM@KUBEJS]: mixing.js loaded')

ServerEvents.recipes(e => {
    e.recipes.create.mixing('kubejs:basic_mech', ['#minecraft:planks', 'create:andesite_alloy', 'create:cogwheel', 'create:shaft'])
    e.recipes.create.mixing('2x kubejs:basic_mech', ['#forge:treated_wood', 'create:andesite_alloy', 'create:cogwheel', 'create:shaft'])
    e.recipes.create.mixing('kubejs:andesite_hull', ['create:andesite_casing', 'kubejs:basic_mech'])
    e.recipes.create.mixing('4x #forge:ingots/rose_gold', ['3x #forge:ingots/copper', '#forge:ingots/gold']).heated()
    // e.recipes.create.mixing('2x #forge:ingots/constantan', ['#forge:ingots/copper', '#forge:ingots/nickel']).heated()
    e.recipes.create.mixing('3x #forge:ingots/invar', ['2x #forge:ingots/iron', '#forge:ingots/nickel']).heated()
    // e.recipes.create.mixing('2x #forge:ingots/electrum', ['#forge:ingots/gold', '#forge:ingots/silver']).heated()
    e.recipes.create.mixing('4x #forge:ingots/bronze', ['3x #forge:ingots/copper', '#forge:ingots/tin']).heated()
    // e.recipes.create.mixing('minecraft:calcite', ['minecraft:stone', 'minecraft:bone_meal']).heated()
    e.recipes.create.mixing(['kubejs:computing_core_base', 'ae2:logic_processor', 'ae2:calculation_processor', 'ae2:engineering_processor'], ['kubejs:computing_core_overflowing', Fluid.of('minecraft:water', 100)])
    e.recipes.create.mixing('kubejs:computing_core_base', 'kubejs:computing_core_corrupted').heated()
    e.recipes.create.mixing(['kubejs:computing_core_base', 'ae2:logic_processor', 'ae2:calculation_processor', 'ae2:engineering_processor'], 'kubejs:computing_core_misaligned')
    e.recipes.create.mixing(Fluid.of('kubejs:thermal_paste', 1000), ['minecraft:blaze_powder', 'thermal:basalz_powder', 'thermal:blitz_powder', 'thermal:blizz_powder', Fluid.of('pneumaticcraft:plastic', 1000)])
    e.recipes.create.mixing('2x extendedcrafting:luminessence', [Fluid.of('thermal:glowstone', 500), 'minecraft:gunpowder', 'minecraft:redstone']).superheated()
    e.recipes.create.mixing(Item.of('powah:dielectric_paste', 32), [Fluid.of('kubejs:blazing_pyrotheum', 250), '3x #minecraft:coals', Item.of('minecraft:clay_ball', 2)])
    e.recipes.create.mixing(Fluid.of('kubejs:refined_mixture', 500), [Fluid.of('starbunclemania:source_fluid', 500), '4x extendedcrafting:luminessence', '4x thermal:blitz_powder']).superheated()
    e.recipes.create.mixing(Fluid.of('kubejs:shadow_essence', 500), [Fluid.of('starbunclemania:source_fluid', 500), '4x mekanism:enriched_carbon', '4x thermal:basalz_powder']).superheated()
    e.recipes.create.mixing('kubejs:dark_essence', [Fluid.of('kubejs:shadow_essence', 250), 'botania:pixie_dust']).superheated()
    e.recipes.create.mixing('kubejs:light_essence', [Fluid.of('kubejs:refined_mixture', 250), 'botania:pixie_dust']).superheated()
    e.recipes.create.mixing('kubejs:light_primordial_stone', [Fluid.of('kubejs:liquid_sunlight', 250), 'kubejs:primordial_stone', 'kubejs:enriched_light_essence']).superheated()
    e.recipes.create.mixing('kubejs:heavy_primordial_stone', [Fluid.of('kubejs:liquid_darkness', 250), 'kubejs:primordial_stone', 'kubejs:enriched_dark_essence']).superheated()
    e.recipes.create.mixing('kubejs:prismatic_primordial_stone', [Fluid.of('kubejs:liquid_ghosts', 250), 'kubejs:primordial_stone', 'botania:dragonstone']).superheated()
    e.recipes.create.mixing('createchromaticreturn:shadow_steel', [Fluid.of('kubejs:shadow_essence', 250), '16x createchromaticreturn:chromatic_compound']).superheated()
    e.recipes.create.mixing('createchromaticreturn:refined_radiance', [Fluid.of('kubejs:refined_mixture', 250), '16x createchromaticreturn:chromatic_compound']).superheated()
    e.recipes.create.mixing('kubejs:juiced_log', ['#minecraft:logs', Fluid.of('thermal:resin', 125)]).heated()

})
